FROM treeverse/lakefs:latest

USER root

# This path must match your local folder structure
COPY scripts/start_lakefs.sh /start_lakefs.sh
RUN chmod +x /start_lakefs.sh

ENTRYPOINT ["/start_lakefs.sh"]