FROM python:3.13-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN pip install uv

COPY pyproject.toml api.py ./

RUN uv pip install --system fastapi uvicorn[standard] pydantic mlflow pandas scikit-learn xgboost

EXPOSE 8080

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8080"]